### PR TITLE
Trigger `score-submission` CI job on pull requests

### LINKED ISSUE #53: Pushing to fork or creating PR to origin didn't seem to kick off build
I don't see the Gitlab actions kicking off in my `main` branch on my `ivcurves` fork:

https://github.com/markcampanelli/ivcurves

or in the corresponding PR to the origin:

https://github.com/cwhanse/ivcurves/pull/52

### PR DESCRIPTION
**Pull request by kandersolar**
Closes #53

### CODE REVIEW

**Comment by markcampanelli** [comment]
@kandersolar ~Can/should we disable the "Read pull request config" workflow for `pull_request`s?~

I was associating this breakage with trying to pull PRs for previous submissions, but I was wrong.

**Comment by markcampanelli** [comment]
I'll add this simple change to https://github.com/cwhanse/ivcurves/pull/52 and see what happens...

**Comment by markcampanelli** [comment]
@kandersolar I added the change here to https://github.com/cwhanse/ivcurves/pull/52, and it seemed to work.

Thanks for figuring this out :).

**Comment by cwhanse** [comment]
@kandersolar can you reopen this and I'll merge? Better to keep this change separate from #52, in case that submission is withdrawn.

**Pull request merged**
