### PR TITLE
Change elementary charge

### LINKED ISSUE #20: Change to exact value for elementary charge
We left off the [last digit.](https://github.com/cwhanse/ivcurves/blob/09caa633c98b28891d84a56ae5d848b12920bf82/ivcurves/utils.py#L38) Should be 1.602176634×10−19

https://www.bipm.org/en/publications/si-brochure/

### PR DESCRIPTION
**Pull request by reepoi**
Closes #20.

Changes the electron/elementary charge in `ivcurves/utils.py` to match the value here: https://www.bipm.org/en/publications/si-brochure/.

Also, adds three more significant digits after the decimal place to each test set's numbers. Now when these values are used to calculate the difference between the left and right side of the single diode equation, the difference is less than `1e-16`.

### CODE REVIEW

**Comment by AdamRJensen** [comment]
Just as a comment, it's possible to get the value for the constant from Scipy as well: https://docs.scipy.org/doc/scipy/reference/constants.html

**Comment by reepoi** [comment]
If we use `scipy.constants`, we should require a minimum version of SciPy because the value of Boltzmann's constant changes depending on the SciPy version. The value for SciPy 1.9.3 is `1.602176634e-19 C`, which matches the value hard-coded here; however, the value is `1.6021766208e-19 C` for SciPy 1.2.0. It changes in SciPy 1.4.0.

**Comment by AdamRJensen** [comment]
> If we use `scipy.constants`, we should require a minimum version of SciPy because the value of Boltzmann's constant changes depending on the SciPy version. The value for SciPy 1.9.3 is `1.602176634e-19 C`, which matches the value hard-coded here; however, the value is `1.6021766208e-19 C` for SciPy 1.2.0. It changes in SciPy 1.4.0.

It sounds like hard-coding it might be the better option.

**Comment by cwhanse** [comment]
> It sounds like hard-coding it might be the better option.

I disagree, I think the scipy values should be used here (and in pvlib-python). In the 2019 version of [International System of Units (SI)](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.330-2019.pdf) there was a significant change in approach to defining the seven fundamental constants, which are now specified _exactly_ and without stated uncertainty. That's why scipy's value changed. I don't think the SI or scipy values are likely to change for the foreseeable future.

**Pull request merged**
