### PR TITLE
Add Compare Submissions Page, Update How to Participate

### LINKED ISSUE #9: Add link to documentation from Leaderboard

### PR DESCRIPTION
**Pull request by reepoi**
Closes #9, #19.

- Added a new Compare Submissions page with a table showing all the individual scores for each test set. The table's columns are sortable. View [demo](https://reepoi.github.io/ivcurves/compare_submissions.html#compare-submissions).
- Leaderboard page changes: View [demo](https://reepoi.github.io/ivcurves/leaderboard.html).
  - Added a link to Compare Submissions page.
  - Added links to the code and documentation of a submission from its leaderboard entry.
- Added a new Python script to generate the `.rst` files needed to document a submission.
- How to Participate changes: View [demo](https://reepoi.github.io/ivcurves/participating.html).
  - Updated the helper functions in "Reading IV Curve JSON Test Sets" to work with the current IV Curve JSON Schema.
  - Updated "Documenting Your Submission" to only have instructions for using the `.rst` file generation Python script.

### CODE REVIEW

**Comment by cwhanse** [comment]
Add overall score to Compare Submissions page

**Comment by reepoi** [comment]
Updates to the pull request:
- Added Overall Scores column to the Compare Submissions page.
- Added Method Name column to the Leaderboard and Compare Submissions pages. The method name entry is based on the title of the submission documentation page of the `SUBMISSION_MAIN` python file. For example, if `SUBMISSION_MAIN` is `sandia_simple.py`, the method name will be `sandia_simple`. This can be changed by updating the title in the `sandia_simple.rst` file. Unfortunately, I cannot find a good solution to limiting the number of characters displayed in the entries of the method name column using Sphinx. There are other ways to do this, but they are very complex for what they are trying to achieve. I will create an issue to revisit the character limit later.

The demo links to the leaderboard and compare submissions pages in the pull request description have been updated to display these changes. The first two entries of the tables on each page show the updates. The remaining entries have broken Method Name entries because they refer to documentation pages that do not exist.

**Comment by cwhanse** [comment]
> I cannot find a good solution to limiting the number of characters 

I guess this can be a requirement for humans (both submitters and reviewers/approvers)

**Comment by reepoi** [comment]
@cwhanse This is ready to be merged.

**Pull request merged**
